# Site settings
author: Dani Lima
title: Lost in iteration
header-img: img/home-bg.png
email: daniel.echuaca.lima@gmail.com
copyright_name: Dani Lima
description: > # this means to ignore newlines until "baseurl:"
  Dani's blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Danieleclima

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
